### ISSUE TITLE
Unnecessary "await" statements in asynchronous versions of methods

### ISSUE THREAD

**Issue by klutch1991** [KevinDockx/StreamExtensions#8]
Hi, thanks for useful library provided!
Took a look into source code of asynchronous versions of methods. It seems, like there is no need to use `await` in implementations of some asynchronous versions of extension methods. For example: 

```
       public static async Task<T> ReadAndDeserializeFromJsonAsync<T>(
            this Stream stream,
            Encoding encoding)
        {
            return await ReadAndDeserializeFromJsonAsync<T>(stream, encoding, true,
                Defaults.DefaultBufferSizeOnRead, false);
        }
```
AFAIK, pure `Task `can be returned here without `await`, so that boilerplate async state machine is not generated. Could be a simple performance improvement.
Please, take a look. I'd be happy to contribute.

**Comment by KevinDockx** [comment]
You could indeed return that Task from the underlying method, and in this specific case that would make sense - yet I prefer to create a new one for each method scope to avoid unintended issues/bugs later on due to leaking.  I wrote up my opinion on that here: https://blog.jetbrains.com/dotnet/2019/01/24/best-practices-building-async-apis-asp-net-core-webinar-recording/ (in the comments - Maarten Balliauw posted it for me) - but of course opinions may vary :)
